"""empty message

Revision ID: 5f199d7c4df2
Revises: 
Create Date: 2024-04-03 19:44:35.373121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f199d7c4df2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('subscription_date', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('payment_id', sa.String(length=50), nullable=False))
    op.drop_column('subscription', 'renewal_date')
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.add_column('subscription', sa.Column('renewal_date', sa.DATE(), nullable=True))
    op.drop_column('subscription', 'payment_id')
    op.drop_column('subscription', 'subscription_date')
    op.drop_column('subscription', 'amount')
    # ### end Alembic commands ###
